name: Setup Python environment
description: Check out, setup Python and reuse/create venv cache

inputs:
  python-version:
    required: true
  venv-dir:
    required: true
  cache-key:
    required: true

  prek-home:
    required: false
    default: "~/.cache/prek"
  fail-on-miss:
    required: false
    default: "true"  # Default fail if not available
  clone-core:
    required: false
    default: "false"  # Clone core (for integrations)

  manual_clone_ha:
    required: false
    default: "manual_clone_ha"  # Directory for original clone

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
      id: python
    - uses: plugwise/gh-actions/restore-venv@v1
      with:
        cache-key: ${{ inputs.cache-key }}
        python-version: ${{ steps.python.outputs.python-version }}
        venv-dir: ${{ inputs.venv-dir }}
        prek-home: ${{ inputs.prek-home }}
        fail-on-miss: ${{ inputs.fail-on-miss }}
        clone-core: ${{ inputs.cone-core }}
        manual_clone_ha: ${{ inputs.manual_clone_ha }}
