name: Setup Python environment
description: Check out, setup Python and reuse/create venv cache

inputs:
  python-version:
    required: true
  venv-dir:
    required: true
  precommit-home:
    required: true
  cache-key:
    required: true

  fail-on-miss:
    required: false
    default: "true"  # Default fail if not available

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
      id: python
    - uses: plugwise/gh-actions/restore-venv@v1
      with:
        cache-key: ${{ inputs.cache-key }}
        python-version: ${{ steps.python.outputs.python-version }}
        venv-dir: ${{ inputs.venv-dir }}
        precommit-home: ${{ inputs.precommit-home }}
        fail-on-miss: ${{ inputs.fail-on-miss }}
