name: "Restore venv and pre-commit from cache"
description: "Restores the venv and pre-commit cache or fails"

inputs:
  python-version:
    required: true
  venv-dir:
    required: true
  precommit-home:
    required: true
  cache-key:
    required: true

  fail-on-miss:
    required: false
    default: "true"  # Default fail if not available
  clone-core:
    required: false
    default: "false"  # Clone core (for integrations)

  manual_clone_ha:
    required: false
    default: "manual_clone_ha"  # Directory for original clone

runs:
  using: "composite"
  steps:
    - name: Create or reuse cache
      id: cache-create
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.venv-dir }}
          ${{ inputs.precommit-home }}
          ${{ inputs.manual_clone_ha }}
        key: ${{ inputs.cache-key }}

    - name: Create Python virtual environment
      if: ${{ steps.cache-create.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        # 20250623 remove pytest-homeassistant-custom-component when present (not needed for)
        sed -i".sedbck" '/pytest-homeassistant-custom-component/d' requirements_*.txt
        # /20250623 remove pytest_homeassistant_custom_component when present (not needed for)
        echo ""
        echo "** Prepare virtualenv**"
        echo ""
        pip install virtualenv --upgrade
        python -m venv ${{ inputs.venv-dir }}
        source venv/bin/activate
        echo ""
        echo "** Install dependencies**"
        echo ""
        pip install uv
        uv pip install -U pip setuptools wheel
        uv pip install --upgrade -r requirements_commit.txt -r requirements_test.txt -c https://raw.githubusercontent.com/home-assistant/core/dev/homeassistant/package_constraints.txt -r https://raw.githubusercontent.com/home-assistant/core/dev/requirements_test.txt -r https://raw.githubusercontent.com/home-assistant/core/dev/requirements_test_pre_commit.txt
        uv pip install --upgrade pytest-asyncio
        echo ""
        echo "** Pre-commit instal**"
        echo ""
        pre-commit install-hooks
        echo ""
        echo "** Cloning/preparing HA core **"
        echo ""
        git clone https://github.com/home-assistant/core.git ha-core
        cp -a ha-core manual_clone_ha

    - name: Save cache if (purposely) created
      if: ( ${{ inputs.fail-on-miss == 'false' && steps.cache-create.outputs.cache-hit != 'true' }} ) || ( always() && ${{ inputs.run-command != '' }} )
      uses: actions/cache/save@v4
      with:
        key: ${{ inputs.cache-key }}
        path: |
          ${{ inputs.venv-dir }}
          ${{ inputs.precommit-home }}
          ${{ inputs.manual_clone_ha }}

    - name: Fail job if Python cache restore failed
      if: ${{ inputs.fail-on-miss == 'true' && steps.cache-create.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        echo "Failed to restore cache for ${{ inputs.python-version}} virtual environment from cache"
        exit 1
